// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARf3dDeqg6ulSfL9SbAGZTu0CGrNj4euA',
    appId: '1:984123815169:web:5c567065a10b92b8891700',
    messagingSenderId: '984123815169',
    projectId: 'gharsat-ward',
    authDomain: 'gharsat-ward.firebaseapp.com',
    storageBucket: 'gharsat-ward.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCztTNwv28LQ6Y2KOgRP3fws1wYjMsVJtw',
    appId: '1:984123815169:android:467fd16938e47b43891700',
    messagingSenderId: '984123815169',
    projectId: 'gharsat-ward',
    storageBucket: 'gharsat-ward.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyTslu5d_L-1wIfu3IeGGy36sKTqlhM80',
    appId: '1:984123815169:ios:15a6e109eb407cc0891700',
    messagingSenderId: '984123815169',
    projectId: 'gharsat-ward',
    storageBucket: 'gharsat-ward.firebasestorage.app',
    iosBundleId: 'ca.dinspire.gharsat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyTslu5d_L-1wIfu3IeGGy36sKTqlhM80',
    appId: '1:984123815169:ios:15a6e109eb407cc0891700',
    messagingSenderId: '984123815169',
    projectId: 'gharsat-ward',
    storageBucket: 'gharsat-ward.firebasestorage.app',
    iosBundleId: 'ca.dinspire.gharsat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARf3dDeqg6ulSfL9SbAGZTu0CGrNj4euA',
    appId: '1:984123815169:web:7cc51f88f9cebdf6891700',
    messagingSenderId: '984123815169',
    projectId: 'gharsat-ward',
    authDomain: 'gharsat-ward.firebaseapp.com',
    storageBucket: 'gharsat-ward.firebasestorage.app',
  );

}
